### ISSUE TITLE
update project list and types

### ISSUE THREAD

**Issue by mellybelly** [data2health/website#103]
suggest that the dropdowns under "current projects" be updated.

remove operational architecture, this is not of community relevance
Rename "sandbox" projects to "cloud sandbox"
Move Maturity Models to "infrastructure" 
(should infrastructure be called "Core project" instead?)

We should discuss what to do with the Cloud DUA, it has essentially been subsumed by the cloud architecture.

**Comment by amvolz** [comment]
Projects are updated for Phase IV
