### ISSUE TITLE
Search needs improvement

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#13]
https://ctsa.ncats.nih.gov/cd2h/

search for “cohort” and you don’t retrieve anything (such as i2b2)

**Comment by jmcmurry** [comment]
This particular search may no longer be super relevant but search still could be improved. I'm wondering how github pages would fare in this over wordpress. cc: @eichmann

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site is searchable.
