### ISSUE TITLE
Add community events to "news and events"

### ISSUE THREAD

**Issue by mellybelly** [data2health/website#2]
CD2H website should highlight activities such as https://www.academyhealth.org/HCDC
on our site.

It would be great if there was a way to suggest events and have them show up on the news and events automatically, as well as on the calendar.

**Comment by cgcook** [comment]
The AcademyHealth data challenge is now on the website: https://ctsa.ncats.nih.gov/cd2h/2019/01/29/healthiest-communities-data-challenge/

[Here is a draft news/events intake form ](https://goo.gl/forms/oNRwaKDo9niA2BLJ2)  
We can embed this either on the website, or within the team portal.  Do we want this public facing?

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site has community events on calendar that writes to the homepage.
