### ISSUE TITLE
update brochure for overall program

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#21]
- [ ] The two-pager has an odd layout 
- [ ] takes 40 seconds to load 
- [ ] it is a single page when printed, so I would call it a one-pager), should change to one pager
- [ ] On the two-pager, it says to get involved in various ways, but there isn’t any further information as to how to attend the meetings, or sign up for the newsletter, etc. - please add 2-pager version with live links 
- [ ] On the two-pager, in the first sentence, “The” should be lowercase 
- [ ] The two-pager mentions a Discovery Storefront which is not found on the site.  I presume this is the faceted search variant of CTSAsearch?

**Comment by nicolevasilevsky** [comment]
https://ctsa.ncats.nih.gov/cd2h/about-us/

**Comment by jmcmurry** [comment]
The details here may no longer be relevant. I'm not sure I ever saw the "two pager" but this basic high-level overview is still needed. I will assign myself ...

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site has updated brochure.
