### ISSUE TITLE
Update citation guidelines on footer of about us page

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#22]
- [ ] The citation guidelines at the bottom should not be centered, it is hard to read. 
- [ ] Maybe also located somewhere else easier to find on site. 
- [ ] please also add link to footer

**Comment by nicolevasilevsky** [comment]
https://ctsa.ncats.nih.gov/cd2h/about-us/

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site has correct citation presentation.
