### ISSUE TITLE
add additional photos to website

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#29]
https://ctsa.ncats.nih.gov/cd2h/workgroup/people-expertise-attribution/

All of the images are very clinical - would be great to get some real-life images of teams working together, a workshop, etc.

**Comment by jmcmurry** [comment]
Did my best to make less doctor-ey; I think it is a lot better. Not a lot of good alternatives. Closing for now. We tried the crowdsourcing of photos that would work for this and did not get any uptake.
