### ISSUE TITLE
updates to CD2H LABS page

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#31]
https://ctsa.ncats.nih.gov/cd2h/innovate-with-us/cd2h-labs/

- [ ] We seem to be missing CTSAsearch. We should make sure other tools are there too. 
- [ ]  Can we use the CD2H labs logo as part of the header image? Otherwise it takes up a ton of space before you get to real content.
- [ ]  There were multiple projects in phase 1 listed here - they’ve not gone away and should be migrated to this page. - Seems we are missing CTSA Search but all the other prototypes from the old labs page  should all be there. - Please add CTSA Search

**Comment by jmcmurry** [comment]
no longer an issue
