### ISSUE TITLE
update spacing in header menu in tools for CTSAs page

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#32]
https://ctsa.ncats.nih.gov/cd2h/tools-for-ctsas/

Header menu under photo - spacing is not the same (between “Informatics maturity model” and “education initiatives”)

![image](https://user-images.githubusercontent.com/6722114/52510226-08991780-2bb0-11e9-91de-59e80083c5e4.png)

**Comment by nicolevasilevsky** [comment]
I think this might be fixed? Looks okay to me.

**Comment by jmcmurry** [comment]
No longer an issue
