### ISSUE TITLE
Best practice guides issues

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#33]
https://ctsa.ncats.nih.gov/cd2h/tools-for-ctsas/#best

- [ ] not scaling correctly

- [ ] remove hyperlinks to text that says 'coming soon', that is misleading

![image](https://user-images.githubusercontent.com/6722114/52512199-734e5100-2bb8-11e9-9bdb-8ce98d6c8e05.png)

**Comment by jmcmurry** [comment]
no longer an issue
