### ISSUE TITLE
Add additional tools to Tools for CTSAs page

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#38]
https://ctsa.ncats.nih.gov/cd2h/tools-for-ctsas/

comment from [google doc](https://docs.google.com/document/d/1rQ1_hzY4HilH2D9tPRFJvz8n--VZrxOU9gn2EjnsPDk/edit):

Was this list crowdsourced? It seems like there are some missing tools.  This would be a great opportunity for the CD2H team/our hubs to weigh in. 

MH- yes this was my suggestion too. I think when we advertise the new site and on the site itself, it should say “your tool here” or somesuch. 

SB: Yes, this was the plan. “Add your tool here” button will be added to site soon. Initial list was generated at the IT Infrastructure strategy meeting in late October.

**Comment by nicolevasilevsky** [comment]
additional request:
No link to “[Managing informatics teams for administrators](https://data2health.github.io/mtip-tutorial/)” course materials or information

**Comment by jmcmurry** [comment]
No longer an issue
