### ISSUE TITLE
Update blog categories on News and Events page

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#42]
https://ctsa.ncats.nih.gov/cd2h/news-events/
 
Update blog categories and sort accordingly [all blog entries, Newsletters, iDTF meetings (Show and Tells, Lead meetings, Full member updates), Workgroup community meetings, other meetings, workshops

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site has updated blog section.
