### ISSUE TITLE
Link to feedback form

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#46]
some kind of feedback mechanism?

**Comment by nicolevasilevsky** [comment]
@jmcmurry is working on a feedback form, from what I understand

**Comment by jmcmurry** [comment]
We decided to opt for making the operations repo the place for this. It is going to be open to team  the data2health/allhands team.

**Comment by nicolevasilevsky** [comment]
So we should link this page from the website?
https://github.com/data2health/operations/issues

Would you like it on the footer? or somewhere else?

**Comment by jmcmurry** [comment]
cd2h.org/feedback is a more accessible route for this and allows for private contributions as desired. It just needs to be linked from more places on the site.

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site has linked feedback form.
