### ISSUE TITLE
add contact info

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#47]
on the [google doc](https://docs.google.com/document/d/1rQ1_hzY4HilH2D9tPRFJvz8n--VZrxOU9gn2EjnsPDk/edit), there is a request for "contact", but there is a contact us button the bottom of the [webpage](https://ctsa.ncats.nih.gov/cd2h/about-us/)

do we want to add contact info for each individual person?

related to #24

**Comment by nicolevasilevsky** [comment]
@mellybelly @jguinney @cgchute @kristiholmes @prpayne5 @pnrobinson @newgene @eichmann 

would you want your contact info included on the website, or do you just want to have the generic 'contact us' at the bottom?

**Comment by jmcmurry** [comment]
each core has a contact; this is adequate for now
