### ISSUE TITLE
update blog content

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#48]
current /future news or event info - everything in the blog (was) in the past

https://ctsa.ncats.nih.gov/cd2h/blog/

I think this is done? assigning @cgcook, but not sure who actually updates this

**Comment by nicolevasilevsky** [comment]
also recommend reordering the blog events, the most distant event is listed first, which is in Nov, and you have to scroll down to the bottom to see the events that are coming up sooner.

Also should remove events that have already happened, like the show and tell on Jan 04

**Comment by jmcmurry** [comment]
I too find the news and blogs page to be very VERY unweildy for exactly this reason, however we need the old events to remain as they house the links to slides and video. Would like to overhaul this in fullness of time.

**Comment by cgcook** [comment]
New website; closing ticket.
