### ISSUE TITLE
Import issues from website feedback gdoc

### ISSUE THREAD

**Issue by jmcmurry** [data2health/website#5]
Import from [here](https://docs.google.com/document/d/1rQ1_hzY4HilH2D9tPRFJvz8n--VZrxOU9gn2EjnsPDk/edit).

**Comment by jmcmurry** [comment]
@nicolevasilevsky is also going to help with this.

**Comment by nicolevasilevsky** [comment]
this is done, everything has been added as an issue in this repo and cross referenced in the google doc

**Comment by nicolevasilevsky** [comment]
note - I didn't assign anyone to tickets though (for the most part)

**Comment by cgcook** [comment]
Thanks Nicole!
