### ISSUE TITLE
Welcome to CD2H looks like a popup

### ISSUE THREAD

**Issue by hsolbrig** [data2health/website#53]
The color and offset nature of the "Welcome to CD2H" box looks like a popup.  I keep looking for the close box in the rhs. Recommend blending withe background or doing something else to make it clear it is integral to the backing photo...

**Comment by RoseRelevo** [comment]
users will be looking for [close] and [x] because other websites have ruined this for us.

**Comment by jmcmurry** [comment]
I believe this has been addressed
