### ISSUE TITLE
Outputs

### ISSUE THREAD

**Issue by RoseRelevo** [data2health/website#59]
you should have a publications tab where one can search for all publications from the program.  As a user I'm always looking for that, and I think our new data scraping took, could be worked backwards, to  get the publications.

**Comment by kristiholmes** [comment]
I'd suggest that we make it easier to openly share any resulting output (e.g., code, data sets, white papers, surveys, etc.).

**Comment by jmcmurry** [comment]
Prob best to organize these by core; @eichmann a md?

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site has projects linked to GitHub pages if applicable.
