### ISSUE TITLE
We need a team page with info about sites and people

### ISSUE THREAD

**Issue by newgene** [data2health/website#61]
where we can put the correct site logos/names to use

People info can be the updated graph visualization @eichmann showed before.

**Comment by jmcmurry** [comment]
The [current our team page](https://ctsa.ncats.nih.gov/cd2h/our-team/) has just the leads; we should mention that participants in each project are shown on the pages. Please deposit the logos you'd like used. See https://github.com/data2health/operations/issues/33 for details.

**Comment by amvolz** [comment]
4 team pages have now been created in the Drupal site with headshots, credentials, titles, and links to their institution webpage for contact and bio information.
