### ISSUE TITLE
CTSA hub logos

### ISSUE THREAD

**Issue by sdmooney** [data2health/website#63]
It would be nice to get the logos of the CTSAs that are CD2H sites on the website somewhere.  Maybe on the bottom of the 'about us' page?  I get a lot of internal feedback from my ctsa ITHS about doing this better

**Comment by jmcmurry** [comment]
This is dependent on https://github.com/data2health/operations/issues/33 where the logos to use are declared / deposited.

**Comment by amvolz** [comment]
Logos have been uploaded to website for CD2H funded hubs. A map now designates the location of participating CTSA hubs.

**Comment by amvolz** [comment]
WordPress site is defunct.
Drupal CD2H site has hub map and logos.
