### ISSUE TITLE
Grant number missing from site

### ISSUE THREAD

**Issue by jmcmurry** [data2health/website#64]
- [x] The Grant number should be in footer of every page 
- [x] At least for now should be on the home page somewhere

https://ctsa.ncats.nih.gov/cd2h/

reported by @kristiholmes [here](https://github.com/data2health/operations/issues/53)

**Comment by cgcook** [comment]
Currently there is a citation link in the footer of every page of the site that redirects to the [about us](https://ctsa.ncats.nih.gov/cd2h/about-us/) page, where the full grant number is referenced.  

Is this sufficient?

**Comment by jmcmurry** [comment]
I don't think we have the citation link there anymore

**Comment by cgcook** [comment]
added link to citation info in footer of site. I've asked Mike to add the text directly to the footer block, as that element doesn't seem editable on my end.
