### ISSUE TITLE
Identify migrated legacy content to be published

### ISSUE THREAD

**Issue by eichmann** [data2health/website#71]
- [ ] Identify who the decisionmakers are for what content should be migrated
 - [ ]  Walk through the existing site and annotate what should be:
   - [ ]  Omitted 
   - [ ]  Updated
   - [ ]  Added as-is to the new site

**Comment by jmcmurry** [comment]
- [ ]  Identify who the decisionmakers are for what content should be migrated
 - [ ]  Walk through the existing site and annotate what should be:
   - [ ]  Omitted 
   - [ ]  Updated
   - [ ]  Added as-is to the new site

**Comment by jmcmurry** [comment]
@amvolz will walk through existing content for each core during the regularly scheduled core meetings with NCATS.

**Comment by amvolz** [comment]
Decision made 1/22/2020 to not have Cores decide now on migrated content. Instead, all content will be migrated to the Drupal prototype, and then decisions can be made by Core Leads through testing, focus groups, etc.

**Comment by eichmann** [comment]
All legacy content has been migrated from WordPress and staged in Drupal mostly as Basic pages. We'll address the remaining nuances as we hone the new site.
