### ISSUE TITLE
Define roles and authorities

### ISSUE THREAD

**Issue by eichmann** [data2health/website#74]
Which roles get to do what with respect to content creation and publishing?

**Comment by eichmann** [comment]
We now have authors, editors and administrators.  Authors can only create new content and edit their own content.  Editors can manipulate overall content state, but not layout/structure/etc.

**Comment by amvolz** [comment]
I think Core PIs and PMs should be made Authors. I'll put on agenda for Weds 3/4 meeting.

**Comment by amvolz** [comment]
After further development, user testing, NCATS feedback, and deployment, I feel only Andrea and web team in Iowa should have editing permissions in Drupal to limit confusion and ensure compliance with decisions.
