### ISSUE TITLE
define core information model

### ISSUE THREAD

**Issue by eichmann** [data2health/website#79]

**Comment by eichmann** [comment]
We have at this point content types of Core, Project, Bio and News Item.  Cross-linking is currently done using entity references.  I've installed the Paragraphs and Paragraph Grid modules to explore more interesting structuring of content.

**Comment by amikaili** [comment]
There are also view artifacts (building blocks) referred to as *Sections*:

When working with an empty layout, the first step is to add a Section. Sections are the top-level building blocks of Page Layouts. They’re added by clicking “Add Section”

After clicking “Add Section”, you select a layout for the section. Layout Builder comes with four Section Layouts: One Column, Two Column, Three Column, and Four Column. Additional layouts can be added as needed.

Some Section Layouts have additional configuration options that must be selected before they are added to a Section. For example, for the Two Column, you must choose the column widths before it is added to the Section. (these widths can be changed later as needed)

Once a section is added, it’s time to add content to your layout. Each column (or region) has an “Add Block” link.. Clicking “Add Block” opens a dialog where you can choose the content to add.

Note that while these links are labeled "Add Block", and the dialog is titled "Choose a block" the items that can be added extend well beyond what is available in Drupal's Block UI. In addition to all blocks available in Block UI, you can create custom blocks that are only used within the Layout and add fields belonging to the current entity or user.

Clicking "Create Custom Block" allows you to create a custom block that is only available to the Layout - not visible in Block UI. Clicking this will take you to a second form: "Add new inline block". You can choose any of your sites' custom Block types.
Clicking the Block type will take you to the custom Block creation form. Each Block type will have a "Title" field, "Display Title" checkbox, and then the custom Block type fields.
Once complete, click the "Add Block" to add the new block to your layout.

See Issue 82 to enable layouts (Using the "Display Suit)

**Comment by eichmann** [comment]
The current scheme seems sufficient for now.  Everything else will be considered incremental enhancement.
