### ISSUE TITLE
suss out grid layout for entity references

### ISSUE THREAD

**Issue by eichmann** [data2health/website#82]
To make the core directors, etc. lay out more nicely in containing pages (e.g., core instances) we need to figure out how to apply a grid layout to entity references.

**Comment by amikaili** [comment]
I found an Extension Module called Display Suite that would provide drag and drop capability, into many pre-available layouts, for any entity… in the website:

*Display Suites*
 
https://www.youtube.com/watch?v=5awFIQOMNKE&feature=youtu.be
 
https://www.drupal.org/project/ds
 
[Running composer alone did not do the trick(composer require 'drupal/ds:^3.5')]
 
So I downloaded the tar gz from this site (Download page):
https://www.drupal.org/project/ds/releases/8.x-3.5
 
Then in test.cd2h.org I enabled it from Manage top menu ⇒ Extend ⇒ Install New Module

And follow this Readme:
 
-- GETTING STARTED --
 
1. Install Display Suite in the usual way (https://drupal.org/node/895232) -- per above -- done
2. Go to Administration > Structure > Display Suite
   (admin/structure/ds/)
3. Click "Manage display" for the entity (e.g., "User") whose display you like
   to change
4. In the vertical tab "Layout for ... in default" choose the desired layout
(dropdown comes pre-populated with available layouts--see below screen shot)
   template (e.g. "Two column stacked") and click "Apply"
5. Start managing the display by dragging fields to regions
6. Click "Save"
 
I am sharing this Google Doc I just started for Drupal, as well:
https://docs.google.com/document/d/1NuFcXqzB-WIzd0mcfmkEMq-oKQovw3kOB2KpJ8K_12E/edit#

**Comment by eichmann** [comment]
Simple once we know what to do:

- create a grid view definition, under grid settings, uncheck “Default column classes” and specify “views-col” as a Custom column class.
- enable Layout builder for the target page, add the body as a block and then the view as a block
- poof!
