### ISSUE TITLE
Get head shots and bios for all persons with bios

### ISSUE THREAD

**Issue by eichmann** [data2health/website#84]

**Comment by amvolz** [comment]
Emailed 4 Community co-leads for their consent. If yes, requested JPEG, title, credentials, projects/bio information. Emailed Admin staff for the same.

**Comment by amvolz** [comment]
This issue is complete.  All people pictured on site now have a link to their respective bio information. Admin core bio info is less developed (except Melissa & Dave) by design. How can we put the teal circle around each picture to be uniform with the rest?

**Comment by amvolz** [comment]
All headshots have been replaced with plain photo images and no teal circle around borders. Bios are linked to each person's webpage, if applicable.
