### ISSUE TITLE
Create map to color code CD2H-CTSA involvement

### ISSUE THREAD

**Issue by amvolz** [data2health/website#86]
Capability to interface with Awareness Management Platform (AMP) as members join

**Comment by amikaili** [comment]
I don't know if my comment belongs in this ticket, I saw the word "map" in the Subject; anyway I wrote an app today that you provide an input of which states of the union (US) and the output image highlights a geographic map pictorially representing them.  According to this NIH site Maryland and NC are the states NIH has presence in:  https://www.nih.gov/institutes-nih/nih-institute-center-contact-information?

**Comment by amikaili** [comment]
<img width="1170" alt="Screen Shot 2020-02-21 at 4 41 02 PM" src="https://user-images.githubusercontent.com/26906359/75077725-399d6f00-54c9-11ea-9883-de6115961857.png">

**Comment by alexisgraves** [comment]
@amikaili I actually have most of the underlying data from developing a previous map I created here: https://labs.cd2h.org/scits/tableau/tableau.jsp. The census data was used to demonstrate additional functionality, but we should be able to use the geo(lat, long, & address)/additional CTSA hub metadata I have within either a D3 visualization or the framework you have. I believe Dave also has this (or similar) data somewhere as well and has used it to create some D3 maps very similar to what was done in Tableau.

**Comment by amikaili** [comment]
https://github.com/amikaili/angular-us-map/blob/master/custom-map-module/src/app/app.component.ts#L10

**Comment by amvolz** [comment]
Holding - need to verify with NCATS if CTSA map is allowed. May have to represent in a different way.

**Comment by eichmann** [comment]
@amvolz check out https://clic-ctsa.org/hubs - hub map is front-and-center.

**Comment by amvolz** [comment]
Drupal site has hub map https://cd2h.org/cd2h_and_ctsa
