### ISSUE TITLE
"Large" images fail to be served to the browser

### ISSUE THREAD

**Issue by eichmann** [data2health/website#88]
This seems to be both just large images (a big png) or high density images.  This show in just a file in the root directory, the hidpi icons for the editor and images in the danland slideshow.

**Comment by amikaili** [comment]
I noticed this anomaly, behaving differently, depending on the setting of the Text format dropdown (see below image).

**Comment by amikaili** [comment]
<img width="1167" alt="Screen Shot 2020-02-21 at 4 53 31 PM" src="https://user-images.githubusercontent.com/26906359/75078414-255a7180-54cb-11ea-95b7-ebeeb0603e7e.png">

**Comment by amikaili** [comment]
The four settings of *Text format* can be configured, see below image, by going to the Admin Configuration menu:

**Comment by amikaili** [comment]
<img width="833" alt="Screen Shot 2020-02-21 at 5 45 00 PM" src="https://user-images.githubusercontent.com/26906359/75080772-981b1b00-54d2-11ea-9325-af896efae431.png">

**Comment by amikaili** [comment]
And Configure the attribute configuration, by going to its Configure page (for example for *Full HTML*
 shown below)

**Comment by amikaili** [comment]
<img width="1664" alt="Screen Shot 2020-02-21 at 5 51 31 PM" src="https://user-images.githubusercontent.com/26906359/75080923-21325200-54d3-11ea-94d7-bce8ee9018d2.png">

**Comment by amikaili** [comment]
<img width="1366" alt="Screen Shot 2020-02-21 at 5 53 01 PM" src="https://user-images.githubusercontent.com/26906359/75080969-4757f200-54d3-11ea-822f-ff6313954f65.png">

**Comment by amikaili** [comment]
Please note Max File size limit allowed 8MB in this case, for Images

**Comment by amikaili** [comment]
For example there are two images broken in the Primary Menu (probably exceed max size limit) as captured below.  As far as fixing them, I believe (please correct me if mistaken @eichmann) the images reside in the site database, to which I have no access (even as a site admin)?  
![Screen Shot 2020-02-24 at 11 37 55 AM](https://user-images.githubusercontent.com/26906359/75177252-6933bd80-56fb-11ea-9110-c8c08f585047.png)
![Screen Shot 2020-02-24 at 11 38 49 AM](https://user-images.githubusercontent.com/26906359/75177268-718bf880-56fb-11ea-8d21-fa5922fa7ce6.png)

![Screen Shot 2020-02-24 at 11 40 12 AM](https://user-images.githubusercontent.com/26906359/75177290-7c468d80-56fb-11ea-953d-4db9ac835f65.png)

**Comment by eichmann** [comment]
Yes, I've included those two images in the slide carousel specifically because they exhibit the issue...

**Comment by eichmann** [comment]
Interesting.  Loading the Adobe image as media and as a direct reference (see https://test.cd2h.org/node/150) both work fine...  I've also installed ImageMagick and set that as the image package to no avail for the slideshow.

**Comment by eichmann** [comment]
I created a custom block type of media, instantiated a custom block with the Adobe image, and added it at default and full side to the landing page, and it all worked...

**Comment by eichmann** [comment]
Fixed! The issue turned out to be an overly-aggressive FileMatch regular expression in the virtual host definition that mapped everything to the PHP engine.  Properly specifying the regular expression resulted in everything working properly.  The hidpi icons have been restored as well, since they now load.
