### ISSUE TITLE
lack of attribution for working group members on website

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/website#9]
https://ctsa.ncats.nih.gov/cd2h/about-us/
https://ctsa.ncats.nih.gov/cd2h/join-the-conversation/
https://ctsa.ncats.nih.gov/cd2h/workgroup/people-expertise-attribution/

- [ ] On the website, only the project leads are mentioned on each project page, none of us who are contributors are mentioned anywhere, thereby, not giving us any credit for our contributions and work. We should be on 'about us' page and workgroup pages
- [ ] CTSA PI Focus Group doesn’t list the PIs from CD2H hubs who are attending these calls.  They should be listed in some way - ex officio, advisory, etc.

**Comment by nicolevasilevsky** [comment]
Current plan: “tiles” will be added for each project  and will list leads for each project. There will eventually be a link to approved proposals with full team members listed. Happy to rethink this.

Note- this comment is from the [google doc](https://docs.google.com/document/d/1rQ1_hzY4HilH2D9tPRFJvz8n--VZrxOU9gn2EjnsPDk/edit), not from me.

**Comment by jmcmurry** [comment]
This has been addressed by the team.md; anyone is welcome to reopen if they feel more needs to be done.
