### ISSUE TITLE
Landing page iframes not working on ios/safari

### ISSUE THREAD

**Issue by eichmann** [data2health/website#92]
They show blank.  Plugging the landing page url into

   http://www.tinywebgallery.com/blog/advanced-iframe/free-iframe-checker

yields an issue with X-Frame-Options: SAMEORIGIN in the response headers.

**Comment by eichmann** [comment]
Note that above may be more about whether the landing page is embeddable.

**Comment by eichmann** [comment]
Actually plugging in the NIH FOA embedded_search page into above works fine.

**Comment by amikaili** [comment]
So this is no issue with Chrome over iOS (sorry can't test it myself, I have loaned my tablet out to my mother)

**Comment by eichmann** [comment]
Just checked ios/chrome and the video and foa blocks do render - so it's safari.

**Comment by eichmann** [comment]
Not sure what was happening yesterday, but it's working today...
