### ISSUE TITLE
Style link tags injected into form actions

### ISSUE THREAD

**Issue by eichmann** [data2health/website#93]
This initially cropped up as a glitch preventing submission of layout builder modifications for admin users. Turns out simple entry of new content was broken for author users.  Finally found a lead on the fix at https://www.drupal.org/project/mbase/issues/2984577 - here's the diff now for bootstrap.inc (including a previous mod for a different issue):

```
[guardian:themes/mbase/includes] root# diff bootstrap.inc bootstrap.inc.orig 
130,140d129
< $manipulators = array(
<   // Only show links that are accessible for the current user.
<   array(
<     'callable' => 'menu.default_tree_manipulators:checkAccess',
<   ),
<   // Use the default sorting of menu links.
<   array(
<     'callable' => 'menu.default_tree_manipulators:generateIndexAndSort',
<   ),
< );
< $menu = \Drupal::menuTree()->transform($menu, $manipulators);
606a596,604
>   // Add Bootstrap CSS from CDN.
>   $defaultbs_cdn_css = trim(_mbase_setting('addbscsscdn'));
> 
>   if (!$defaultbs_cdn_css) {
>     $theme_info = \Drupal::service('theme_handler')->listInfo();
>     $defaultbs_cdn_css = $theme_info['mbase']->info['bs-cdn-css'];
>   }
>   $css[$defaultbs_cdn_css] = _mbase_css_alter_array_build($defaultbs_cdn_css, -99.99);
> 
[guardian:themes/mbase/includes] root# 
```

Then I cleared the "Add CSS files from CDN" field in IceMagic Settings > Advanced

**Comment by eichmann** [comment]
Identification and resolution pretty much concurrent...

**Comment by eichmann** [comment]
Yikes - this broke part of the landing page and the social fonts...

**Comment by alexisgraves** [comment]
@eichmann All is well! I added in both the google font CSS and the font-awesome CSS in the Icemagic theme folder and linked them within the icemagic.libraries.yml. I must have toggled the 'Show content region in front page' radio when looking over changes so that removed the home page sections, but a quick toggle back and it is working.

**Comment by eichmann** [comment]
Excellent.
